# Generated by Django 5.1.2 on 2024-10-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
