# Generated by Django 5.1.1 on 2024-10-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_workshop_image_workshop_image_urls_and_more'),
        ('booking', '0003_wishlist'),
    ]

    operations = [
    ]
