# Generated by Django 5.1 on 2024-10-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_workshop_image_workshop_image_urls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopproduct',
            name='stock',
        ),
    ]
