# Generated by Django 5.1.1 on 2024-10-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_merge_20241025_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='workshopproduct',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
