# Generated by Django 5.1 on 2024-10-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_pic',
            field=models.JSONField(default=dict),
        ),
    ]
