# Generated by Django 5.1.2 on 2024-10-27 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_review', '0003_alter_product_id'),
        ('shopping', '0002_alter_order_user_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_review_reviews', to='shopping.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
