# Generated by Django 5.1.2 on 2024-10-27 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_booking_date'),
        ('comment_review', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_review_reviews', to='booking.workshop'),
        ),
    ]
