# Generated by Django 5.1 on 2024-10-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_url', models.URLField()),
                ('store_address', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('image_urls', models.JSONField()),
                ('additional_info', models.TextField()),
                ('product_link', models.URLField()),
                ('category', models.CharField(choices=[('pakaian_pria', 'Pakaian Pria'), ('pakaian_wanita', 'Pakaian Wanita'), ('aksesoris', 'Aksesoris'), ('workshop', 'Workshop')], max_length=50)),
            ],
        ),
    ]
