# Generated by Django 5.1.2 on 2024-10-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
