# Generated by Django 5.1.1 on 2024-10-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_delete_wishlist'),
        ('shopping', '0004_review'),
    ]

    operations = [
    ]
