# Generated by Django 5.1.2 on 2024-10-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_merge_0004_delete_wishlist_0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
